version: '3.4'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      SA_PASSWORD: "YourStrong!Passw0rd"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    restart: always
    networks:
      - app-network

  controlefuncionario:
    build:
      context: .
      dockerfile: ControleFuncionario/Dockerfile
    container_name: controlefuncionario
    depends_on:
      - sqlserver
    environment:
      - ConnectionStrings__DefaultConnection=Server=sqlserver,1433;User Id=sa;Password=YourStrong!Passw0rd;TrustServerCertificate=True;
    ports:
      - "8080:8080"
    restart: always
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
